### ISSUE TITLE
Bug Join/Leave

### ISSUE THREAD

**Issue by MINS646** [Steffion/BlockHunt#308]
org.bukkit.command.CommandException: Unhandled exception executing command 'bh' in plugin BlockHunt v0.2.0_BETA_B5
     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-1627]
     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[minecraft_server.jar:git-Spigot-1627]
     at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[minecraft_server.jar:git-Spigot-1627]
     at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1013) [minecraft_server.jar:git-Spigot-1627]
     at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:850) [minecraft_server.jar:git-Spigot-1627]
     at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [minecraft_server.jar:git-Spigot-1627]
     at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [minecraft_server.jar:git-Spigot-1627]
     at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [minecraft_server.jar:git-Spigot-1627]
     at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [minecraft_server.jar:git-Spigot-1627]
     at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [minecraft_server.jar:git-Spigot-1627]
     at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [minecraft_server.jar:git-Spigot-1627]
     at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [minecraft_server.jar:git-Spigot-1627]
     at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [minecraft_server.jar:git-Spigot-1627]
     at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [minecraft_server.jar:git-Spigot-1627]
Caused by: java.lang.NullPointerException
     at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftInventory.setContents(CraftInventory.java:66) ~[minecraft_server.jar:git-Spigot-1627]
     at nl.Steffion.BlockHunt.ArenaHandler.playerLeaveArena(ArenaHandler.java:346) ~[?:?]
     at nl.Steffion.BlockHunt.Commands.CMDleave.exectue(CMDleave.java:16) ~[?:?]
     at nl.Steffion.BlockHunt.BlockHunt.onCommand(BlockHunt.java:819) ~[?:?]
     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-1627]
Hi this bug please fix and update to 1.7.9

**Comment by Steffion** [comment]
Could you confirm if this is still happening with the latest version?
