### ISSUE TITLE
Error when I right click on a sign!

### ISSUE THREAD

**Issue by Luloo** [Steffion/BlockHunt#309]
[17:48:15 ERROR]: Could not pass event PlayerInteractEvent to Lobby vRelease 4.0

org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:320) ~[Server.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[Server.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:486) [Server.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:471) [Server.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
        at org.bukkit.craftbukkit.v1_7_R1.event.CraftEventFactory.callPlayerInte
ractEvent(CraftEventFactory.java:195) [Server.jar:git-Bukkit-1.7.2-R0.2-50-gdce2
b35-b3019jnks]
        at net.minecraft.server.v1_7_R1.PlayerInteractManager.interact(PlayerInt
eractManager.java:374) [Server.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
        at net.minecraft.server.v1_7_R1.PlayerConnection.a(PlayerConnection.java
:628) [Server.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
        at net.minecraft.server.v1_7_R1.PacketPlayInBlockPlace.a(SourceFile:60)
[Server.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
        at net.minecraft.server.v1_7_R1.PacketPlayInBlockPlace.handle(SourceFile
:9) [Server.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
        at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:146
) [Server.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
        at net.minecraft.server.v1_7_R1.ServerConnection.c(SourceFile:134) [Serv
er.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
        at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:6
55) [Server.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
        at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:2
50) [Server.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
        at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:5
45) [Server.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
        at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java
:457) [Server.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
        at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:6
17) [Server.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
Caused by: java.lang.NullPointerException
        at Lobby.Main.onSignClick(Main.java:136) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0
_67]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0
_67]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.7.0_67]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_67]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:318) ~[Server.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
        ... 15 more

**Comment by Steffion** [comment]
This has nothing to do with BlockHunt. Please contact the developer of 'Lobby vRelease 4.0'
