### ISSUE TITLE
error happends when i join an arena 

### ISSUE THREAD

**Issue by zmw1234** [Steffion/BlockHunt#312]
This error happeneds each time a join an arena on my server 

[15:23:18 INFO]: zmw123 issued server command: /blockhunt join town
[15:23:18 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'blockhunt' in plugin BlockHunt v0.2.0_BETA_B5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[minecraft_server.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[minecraft_server.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [minecraft_server.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [minecraft_server.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [minecraft_server.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [minecraft_server.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [minecraft_server.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [minecraft_server.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [minecraft_server.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [minecraft_server.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [minecraft_server.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [minecraft_server.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [minecraft_server.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
Caused by: java.lang.NoClassDefFoundError: me/libraryaddict/disguise/DisguiseAPI
	at nl.Steffion.BlockHunt.ArenaHandler.playerJoinArena(ArenaHandler.java:234) ~[?:?]
	at nl.Steffion.BlockHunt.Commands.CMDjoin.exectue(CMDjoin.java:21) ~[?:?]
	at nl.Steffion.BlockHunt.BlockHunt.onCommand(BlockHunt.java:819) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	... 13 more
>

**Comment by Steffion** [comment]
Make sure you install the dependencies.
