### ISSUE TITLE
Error when a player leaves the arena.

### ISSUE THREAD

**Issue by EncryptSL** [Steffion/BlockHunt#316]
Server using Spigot 1.7.9 

Error:

org.bukkit.command.CommandException: Unhandled exception executing command 'bh' in plugin BlockHunt v0.2.0_BETA_B5
     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-1487]
     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180) ~[minecraft_server.jar:git-Spigot-1487]
     at org.bukkit.craftbukkit.v1_7_R3.CraftServer.dispatchCommand(CraftServer.java:726) ~[minecraft_server.jar:git-Spigot-1487]
     at net.minecraft.server.v1_7_R3.PlayerConnection.handleCommand(PlayerConnection.java:999) [minecraft_server.jar:git-Spigot-1487]
     at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:830) [minecraft_server.jar:git-Spigot-1487]
     at net.minecraft.server.v1_7_R3.PacketPlayInChat.a(PacketPlayInChat.java:28) [minecraft_server.jar:git-Spigot-1487]
     at net.minecraft.server.v1_7_R3.PacketPlayInChat.handle(PacketPlayInChat.java:65) [minecraft_server.jar:git-Spigot-1487]
     at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:180) [minecraft_server.jar:git-Spigot-1487]
     at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java:81) [minecraft_server.jar:git-Spigot-1487]
     at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:720) [minecraft_server.jar:git-Spigot-1487]
     at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:283) [minecraft_server.jar:git-Spigot-1487]
     at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:583) [minecraft_server.jar:git-Spigot-1487]
     at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:489) [minecraft_server.jar:git-Spigot-1487]
     at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [minecraft_server.jar:git-Spigot-1487]
Caused by: java.util.ConcurrentModificationException
     at java.util.HashMap$HashIterator.nextEntry(HashMap.java:926) ~[?:1.7.0_51]
     at java.util.HashMap$KeyIterator.next(HashMap.java:960) ~[?:1.7.0_51]
     at net.minecraft.server.v1_7_R3.EntityTracker.track(EntityTracker.java:32) ~[minecraft_server.jar:git-Spigot-1487]
     at net.minecraft.server.v1_7_R3.WorldManager.a(WorldManager.java:18) ~[minecraft_server.jar:git-Spigot-1487]
     at net.minecraft.server.v1_7_R3.World.a(World.java:1143) ~[minecraft_server.jar:git-Spigot-1487]
     at net.minecraft.server.v1_7_R3.WorldServer.a(WorldServer.java:835) ~[minecraft_server.jar:git-Spigot-1487]
     at net.minecraft.server.v1_7_R3.World.addEntity(World.java:1136) ~[minecraft_server.jar:git-Spigot-1487]
     at net.minecraft.server.v1_7_R3.World.addEntity(World.java:1063) ~[minecraft_server.jar:git-Spigot-1487]
     at net.minecraft.server.v1_7_R3.PlayerList.moveToWorld(PlayerList.java:549) ~[minecraft_server.jar:git-Spigot-1487]
     at org.bukkit.craftbukkit.v1_7_R3.entity.CraftPlayer.teleport(CraftPlayer.java:503) ~[minecraft_server.jar:git-Spigot-1487]
     at org.bukkit.craftbukkit.v1_7_R3.entity.CraftEntity.teleport(CraftEntity.java:200) ~[minecraft_server.jar:git-Spigot-1487]
     at nl.Steffion.BlockHunt.ArenaHandler.playerLeaveArena(ArenaHandler.java:353) ~[?:?]
     at nl.Steffion.BlockHunt.Commands.CMDleave.exectue(CMDleave.java:16) ~[?:?]
     at nl.Steffion.BlockHunt.BlockHunt.onCommand(BlockHunt.java:824) ~[?:?]
     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-1487]
... 13 more

**Comment by Steffion** [comment]
Could you confirm if this is still happening with the latest version?
