### ISSUE TITLE
error with the beta

### ISSUE THREAD

**Issue by elpedriyo** [Steffion/BlockHunt#346]
[20:49:22] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to BlockHunt v0.2.0_BETA_B5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:472) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at org.bukkit.craftbukkit.v1_7_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:212) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.PlayerInteractManager.dig(PlayerInteractManager.java:103) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.PlayerConnection.a(PlayerConnection.java:548) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.PacketPlayInBlockDig.a(SourceFile:53) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.PacketPlayInBlockDig.handle(SourceFile:8) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:147) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.ServerConnection.c(ServerConnection.java:77) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:700) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:562) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:469) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
Caused by: java.lang.NullPointerException
	at nl.Steffion.BlockHunt.SolidBlockHandler.makePlayerUnsolid(SolidBlockHandler.java:26) ~[?:?]
	at nl.Steffion.BlockHunt.Listeners.OnPlayerInteractEvent.onPlayerInteractEvent(OnPlayerInteractEvent.java:187) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor119.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_80]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:318) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	... 16 more
[20:49:24] [Incoming-1,duckchat,server2/INFO]: [MiniGames][Votante]~LIvanL: que bonito
[20:49:27] [Incoming-2,duckchat,server2/INFO]: [Creativo]JosueTrota321: hola
[20:49:29] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to BlockHunt v0.2.0_BETA_B5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:472) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at org.bukkit.craftbukkit.v1_7_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:212) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.PlayerInteractManager.dig(PlayerInteractManager.java:103) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.PlayerConnection.a(PlayerConnection.java:548) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.PacketPlayInBlockDig.a(SourceFile:53) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.PacketPlayInBlockDig.handle(SourceFile:8) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:147) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.ServerConnection.c(ServerConnection.java:77) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:700) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:562) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:469) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
Caused by: java.lang.NullPointerException
	at nl.Steffion.BlockHunt.SolidBlockHandler.makePlayerUnsolid(SolidBlockHandler.java:26) ~[?:?]
	at nl.Steffion.BlockHunt.Listeners.OnPlayerInteractEvent.onPlayerInteractEvent(OnPlayerInteractEvent.java:187) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor119.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_80]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:318) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
	... 16 more

**Comment by Steffion** [comment]
Is this error still happening with the latest version?
