### ISSUE TITLE
Convertible arenas.yml to the recode or is this an error?

### ISSUE THREAD

**Issue by TNTUP** [Steffion/BlockHunt#364]
Hi, I tried the recode on my test server with my actual arenas from my main server on 1.8.8 and I got an error about serilization things... I guess either not implemented or to be changed? If the arenas.yml needs a reset, an converter can be possible or it will stay the same config as before?

22:42:09] [Server thread/INFO]: [BlockHunt v0.3.0-ALPHA] Enabling BlockHunt v0.3.0-ALPHA
[22:42:09] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: org.yaml.snakeyaml.error.YAMLException: Could not deserialize object
[22:42:09] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56)
[22:42:09] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184)
[22:42:09] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130)
[22:42:09] [Server thread/WARN]: 	at nl.Steffion.BlockHunt.configs.Config.load(Config.java:112)
[22:42:09] [Server thread/WARN]: 	at nl.Steffion.BlockHunt.configs.Config.<init>(Config.java:59)
[22:42:09] [Server thread/WARN]: 	at nl.Steffion.BlockHunt.configs.Config.<init>(Config.java:28)
[22:42:09] [Server thread/WARN]: 	at nl.Steffion.BlockHunt.BlockHunt.onEnable(BlockHunt.java:160)
[22:42:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[22:42:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[22:42:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[22:42:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
[22:42:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
[22:42:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411)
[22:42:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376)
[22:42:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331)
[22:42:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269)
[22:42:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
[22:42:09] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[22:42:09] [Server thread/WARN]: Caused by: org.yaml.snakeyaml.error.YAMLException: Could not deserialize object
[22:42:09] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:37)
[22:42:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
[22:42:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373)
[22:42:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147)
[22:42:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354)
[22:42:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:489)
[22:42:09] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26)
[22:42:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
[22:42:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373)
[22:42:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147)
[22:42:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354)
[22:42:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:489)
[22:42:09] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26)
[22:42:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
[22:42:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
[22:42:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
[22:42:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
[22:42:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369)
[22:42:09] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54)
[22:42:09] [Server thread/WARN]: 	... 17 more
[22:42:09] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Specified class does not exist ('BlockHuntLocation')
[22:42:09] [Server thread/WARN]: 	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:185)
[22:42:09] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35)
[22:42:09] [Server thread/WARN]: 	... 35 more
[22:42:09] [Server thread/INFO]: [BlockHunt v0.3.0-ALPHA] Missing config file has been created. (settings.yml)
[22:42:09] [Server thread/ERROR]: [BlockHunt v0.3.0-ALPHA] Required dependency is not installed! (LibsDisguises)
[22:42:09] [Server thread/WARN]: [BlockHunt v0.3.0-ALPHA] BlockHunt has NOT successfully been loaded!

Arenas.yml: http://i.qcfb.ca/20160408225713.txt

If this issue has been already posted, feel free to close this one as duplicate: )

**Comment by TNTUP** [comment]
Tried the 0.2.0 snapshot build, severe lag on 1.9.2: https://timings.spigotmc.org/?url=15704613 

So Im guessing thats not ready for production use, gladly to test them ;)

**Comment by Steffion** [comment]
The old arenas.yml file is not (yet) compatible with the new version.
I like the idea for a converter.

**Comment by RandomPanda30** [comment]
Pretty confident with working on converters, especially if they're file based. Shall update and keep you posted on what's going on
