### ISSUE TITLE
Crash with typing /blockhunt join (arena name)

### ISSUE THREAD

**Issue by wiepiegames** [Steffion/BlockHunt#369]
[17:21:22 INFO]: wiepiegames issued server command: /BlockHunt join woud
[17:21:22 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'blockhunt' in plugin BlockHunt v0.2.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66-internal]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
Caused by: java.lang.IllegalArgumentException: Health must be between 0 and 3.0
	at org.bukkit.craftbukkit.v1_9_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:95) ~[spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
	at nl.Steffion.BlockHunt.ArenaHandler.playerJoinArena(ArenaHandler.java:148) ~[?:?]
	at nl.Steffion.BlockHunt.Commands.CMDjoin.exectue(CMDjoin.java:21) ~[?:?]
	at nl.Steffion.BlockHunt.BlockHunt.onCommand(BlockHunt.java:826) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
	... 15 more

**Comment by RandomPanda30** [comment]
Simple bug. I'll fix it ASAP

**Comment by wiepiegames** [comment]
Thank you
When coming the update where that will fixed

Sorry fpry bad english I'm Dutch and 12
Op 16 apr. 2016 23:57 schreef "JPanda" <notifications@github.com>:

Simple bug. I'll fix it ASAP

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/Steffion/BlockHunt/issues/369#issuecomment-210912414>
