### ISSUE TITLE
Console Spam (Scoreboard)

### ISSUE THREAD

**Issue by Yuuki2012** [Steffion/BlockHunt#382]
[17:57:22 WARN]: [BlockHunt] Task #456 for BlockHunt v0.2.2-SNAPSHOT generated an exception
java.lang.NullPointerException
        at nl.Steffion.BlockHunt.ScoreboardHandler.updateScoreboard(ScoreboardHandler.java:57) ~[?:?]
        at nl.Steffion.BlockHunt.BlockHunt$3.run(BlockHunt.java:742) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.9.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-e000104-4cb3258]

And I also can't kill hiders, they don't die and are unable to be hit after hitting them once.

Using BlockHunt-v0.2.2-SNAPSHOT.jar

**Comment by Steffion** [comment]
Could you give me a list of the plugins you are running?

**Comment by Yuuki2012** [comment]
If you're gonna ask that, I know the problem already, most likely FeatherBoard... Anyway here it is:
ASkyBlock, Auctions, AutoAFK, Autorank, Bounty, CoreProtect, DynMap, DynMap-Factions, Essentials, Factions, FeatherBoard, GUIShop, ItemSlotMachine (1.9 build), Jobs, LibsDisguises, Lockette, Lottery, MassiveCore, MultiInv, MultiWorld, Mute, PermissionsEx, PlaceholderAPI, PlayerSQL, ProtocolLib, RPGDrop, SimpleGadgets, SkinRestorer, SuperTrails, TuxTwoLib, UltraAuth, Vault, WorldBorder, WorldEdit, WorldGuard.

**Comment by Steffion** [comment]
It is most likely conflicting with FeatherBoard ye..
It is quite hard for developers to prevent issues like these because there are so many plugins out there that could conflict with it. I would suggest you to reconsider using FeatherBoard or disable the scoreboard or something. Other than that I can not help you with this issue.
