### ISSUE TITLE
Book for select block can't be oppened?

### ISSUE THREAD

**Issue by DeadMasterBG** [Steffion/BlockHunt#386]

**Comment by Steffion** [comment]
When trying to open the menu, does it give an error in console? What version of BlockHunt are you running? What version of Bukkit are you running?

**Comment by DeadMasterBG** [comment]
BlockHunt v 0.2.1 bukkit for 1.8

**Comment by DeadMasterBG** [comment]
### Could not pass event PlayerInteractEvent to BlockHunt v0.2.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:210) [craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177) [craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:107) [craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:608) [craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:672) [craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.getItemInMainHand()Lorg/bukkit/inventory/ItemStack;
        at nl.Steffion.BlockHunt.Listeners.OnPlayerInteractEvent.onPlayerInteractEvent(OnPlayerInteractEvent.java:39) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
        ... 18 more

**Comment by DeadMasterBG** [comment]
Owner this bug is only for BlockHunt v.0.2.1.

**Comment by Steffion** [comment]
If your server is still running 1.8 use version v0.2.1-MC1.8.8 which can be found here: http://jenkins.steffion.com/job/BlockHunt-1.8/

If you are running 1.9 or above, run version v0.2.1 which can be found here:
http://dev.bukkit.org/bukkit-plugins/blockhunt/files/


Running the correct version for your Bukkit version will fix the error.
