### ISSUE TITLE
Plugin not loading: Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by ajgeiss0702** [Steffion/BlockHunt#387]
Before I say anything, I just want to say that I have the same problem @john96dk had, but it was marked invalid.
I Checked everything I could think of, including the stuff in CONTRIBUTING.md, and found no issues that may be causing this. I tried the normal version and the rewrite version. Here are the errors:

`rewrite:
[05:56:28 ERROR]: Could not load 'plugins/BlockHunt-v0.3.0-ALPHA.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: nl/Steffion/BlockHunt/BlockHunt : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:296) [spigot.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.reload(CraftServer.java:743) [spigot.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.Bukkit.reload(Bukkit.java:539) [spigot.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-e000104-4cb3258]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_55]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_55]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-e000104-4cb3258]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_55]
Caused by: java.lang.UnsupportedClassVersionError: nl/Steffion/BlockHunt/BlockHunt : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_55]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_55]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_55]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_55]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_55]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_55]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_55]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_55]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_55]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-e000104-4cb3258]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_55]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_55]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_55]
	at java.lang.Class.forName(Class.java:270) ~[?:1.7.0_55]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-e000104-4cb3258]
	... 21 more
normal:
[05:47:17 ERROR]: Could not load 'plugins/BlockHunt-v0.2.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: nl/Steffion/BlockHunt/BlockHunt : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:296) [spigot.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:201) [spigot.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot.jar:git-Spigot-e000104-4cb3258]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_55]
Caused by: java.lang.UnsupportedClassVersionError: nl/Steffion/BlockHunt/BlockHunt : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_55]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_55]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_55]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_55]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_55]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_55]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_55]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_55]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_55]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-e000104-4cb3258]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_55]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_55]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_55]
	at java.lang.Class.forName(Class.java:270) ~[?:1.7.0_55]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-e000104-4cb3258]
	... 6  more

I would add a dropdown thing but I cant find it.

I am running git-Spigot-e000104-4cb3258 (MC: 1.9.2) on my server. A full log of it can be found at http://pastebin.com/TbfMRdfq

**Comment by TNTUP** [comment]
Update Java, I guess Steffion built it on Java 8, I guess the "51" thing is related for Java 7. Please correct me if I'm wrong^^

**Comment by Steffion** [comment]
Make sure you are running Java 8 first, if so I will continue having a look at it.

**Comment by ajgeiss0702** [comment]
I am running Java 8, I made sure before I posted
