### ISSUE TITLE
Error report - spigot1.12.2

### ISSUE THREAD

**Issue by momoservertw** [Steffion/BlockHunt#405]
**Command don't work**

Command "/blockhunt wand" don't work in BlockHunt v0.2.1.
Shows "/blockhunt help" for help
I cannot create any area, that is so sad :(
+
**Console error message**
### 
 [Thread-11/WARN]: Exception in thread "Thread-11" 
[Thread-11/WARN]: java.lang.NullPointerException
 [Thread-11/WARN]: 	at nl.Steffion.BlockHunt.Updater.versionCheck(Updater.java:480)
 [Thread-11/WARN]: 	at nl.Steffion.BlockHunt.Updater.access$400(Updater.java:55)
[Thread-11/WARN]: 	at nl.Steffion.BlockHunt.Updater$UpdateRunnable.run(Updater.java:621)
[Thread-11/WARN]: 	at java.lang.Thread.run(Unknown Source)
-------------------------------------------------------------------------------------------------------------
I download the new version (v0.3.0-ALPHA) at https://github.com/AddstarMC/BlockHunt
It's still has some problem ><
Error report: https://github.com/AddstarMC/BlockHunt/issues/24
-------------------------------------------------------------------------------------------------------------
Spigot 1.12.2 (lastest version, 4/2)
Plugins:
ProtocolLib� (v4.3.0 - https://www.spigotmc.org/resources/protocollib.1997/history)
LibsDisguises� (development builds#199 - https://ci.md-5.net/job/LibsDisguises/lastStableBuild/)
BlockHunt� (0.2.1- https://dev.bukkit.org/projects/blockhunt/files)

**Comment by Steffion** [comment]
The wand tool is disabled by default, check the config.yml to enable the wand if you'd like.
It is not required to set corners of an arena (useful when your arena isn't a cuboid).

**Comment by momoservertw** [comment]
Oh, I see that thank you : )
This version works good in Spigot1.12.2 !
**Setting Notes: Config**
autoUpdateCheck: false  <---Trun on will cause some warning (console)
wandEnabled: true <---Enabled the select tool #need restart
------------------------------------------------------------------------------------------------------------------
**Error Report:**
If you run outside the game area while playing, it will cause error in the console and the player will shuck in the air.

[Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to BlockHunt v0.2.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:580) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:483) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:612) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1346) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity0(EntityHuman.java:846) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:868) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:586) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.EntityMonster.B(EntityMonster.java:68) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.EntityZombie.B(EntityZombie.java:202) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.EntityZombieHusk.B(SourceFile:68) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.PathfinderGoalMeleeAttack.a(SourceFile:127) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.PathfinderGoalMeleeAttack.e(SourceFile:119) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.PathfinderGoalZombieAttack.e(SourceFile:28) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.PathfinderGoalSelector.a(SourceFile:129) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.EntityInsentient.doTick(EntityInsentient.java:664) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2097) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:507) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.EntityMonster.n(EntityMonster.java:24) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.EntityZombie.n(EntityZombie.java:155) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1946) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.EntityMonster.B_(EntityMonster.java:28) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at nl.Steffion.BlockHunt.Listeners.OnEntityDamageByEntityEvent.onEntityDamageByEntityEvent(OnEntityDamageByEntityEvent.java:56) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	... 36 more

**Comment by Steffion** [comment]
The wand tool (including the border enforcement) was causing errors. That is why it got removed. I recommend you to disable it and just add a wall around the arena.
